(* generated by Ott 0.34, locally-nameless from: language.ott *)
Require Import Bool.
Require Import Metalib.Metatheory.
Require Import List.
Require Import Ott.ott_list_core.
(** syntax *)
Definition x : Set := var. (* term variable *)

Inductive e : Set := 
 | ExpressionUnit : e.

Inductive s : Set := 
 | StatementAssign (x5:x) (e5:e)
 | StatementSeq (s1:s) (s2:s)
 | StatementReturn (e5:e).

(* EXPERIMENTAL *)
(** auxiliary functions on the new list types *)
(** library functions *)
(** subrules *)
(** arities *)
(** opening up abstractions *)
(** terms are locally-closed pre-terms *)
(* definitions *)
(** free variables *)
(** substitutions *)

(* definitions *)


(** infrastructure *)


