(* generated by Ott 0.34 from: language.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.



Inductive e : Set := 
 | ExpressionUnit : e.

Inductive s : Set := 
 | StatementSeq (s1:s) (s2:s)
 | StatementReturn (e5:e).


