name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
  pull_request:
    paths-ignore:
      - README.md

permissions:
  contents: read

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build LaTeX document (main)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: PurePy-spec.tex

      - name: Build LaTeX document (with appendix)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: PurePy-spec-full.tex
