name: Python interpreter diff-testing

on:
  push:
    branches: [ "main" ]

jobs:
  discover-tests:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.collect.outputs.tests }}

    steps:
      - uses: actions/checkout@v4

      - id: collect
        run: |
          tests=$(find test -type f -name "*.py" \
            | jq -R -s -c 'split("\n")[:-1]')
          echo "tests=$tests" >> $GITHUB_OUTPUT

  test:
    needs: discover-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_file: ${{ fromJson(needs.discover-tests.outputs.tests) }}
        python-version:
          - '3.10'
          - 'pypy3.10'
          - 'graalpy-24.0'
    name: test (${{ matrix.python-version }} • ${{ matrix.test_file }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run test
        run: test/run-test.sh python ${{ matrix.test_file }}

  test-ironpython:
    needs: discover-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_file: ${{ fromJson(needs.discover-tests.outputs.tests) }}
    name: test (IronPython • ${{ matrix.test_file }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Setup IronPython
        run: | 
          dotnet tool install -g ironpython.console
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run test
        run: test/run-test.sh ipy ${{ matrix.test_file }}

  test-jython:
    needs: discover-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_file: ${{ fromJson(needs.discover-tests.outputs.tests) }}
    name: test (Jython • ${{ matrix.test_file }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Jython
        uses: LukeSavefrogs/setup-jython@v3
        with:
          jython-version: '2.7.3'
        
      - name: Run test
        run: test/run-test.sh jython ${{ matrix.test_file }}
      

      