name: Litmus tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - runtime: CPython
            cli: python
            version: '3.12'

          - runtime: GraalPy
            cli: python --no-mypy
            version: 'graalpy-24.0'

          - runtime: Pyodide
            cli: $PYODIDE_PYTHON --no-mypy
            version: '3.12'

    name: test (${{ matrix.runtime }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: Install mypy
        if: matrix.runtime == 'CPython'
        run: pip install mypy

      - name: Install uv
        if: matrix.runtime == 'Pyodide'
        uses: astral-sh/setup-uv@v6

      - name: Install Pyodide
        if: matrix.runtime == 'Pyodide'
        run: |
          uv python install cpython-3.14.2-emscripten-wasm32-musl
          PYODIDE_PYTHON=$(uv python find cpython-3.14.2-emscripten-wasm32-musl)
          echo "PYODIDE_PYTHON=$PYODIDE_PYTHON" >> "$GITHUB_ENV"
          
      - name: Run all tests
        run: |
          test/run-all.sh ${{ matrix.cli }}
          

